### ISSUE TITLE
PortScan.py file is badly formatted

### ISSUE THREAD

**Issue by Mec-iS** [niloofarkheirkhah/nili#1]
https://github.com/niloofarkheirkhah/nili/blob/master/nili/PortScan.py

Please also consider using [PEP-8 guidelines and tools](https://www.python.org/dev/peps/pep-0008/) (:

**Comment by ehsanmir** [comment]
Thanks for the notice, The [PortScan Module](https://github.com/niloofarkheirkhah/nili/blob/master/nili/PortScan.py) has been fixed. There is lots of work to do and we will consider PEP-8 in the future ;)
