### ISSUE TITLE
Many Problems

### ISSUE THREAD

**Issue by sasatefa2009** [niloofarkheirkhah/nili#2]
THERE IS NO GUIDE OF HOW TO INSTALL NILI !!!!

first of "Netzob"
can not be installed with python3, need to be installed with python2
right command "python setup.py install"

then to install nili 
python setup.py install

then to open nili i got an error when trying to open with python 3
Traceback (most recent call last):
  File "nili.py", line 2, in <module>
    from netzob.all import *
ImportError: No module named 'netzob'

-- btw i've installed nitzob --

but when i try to open nili with python2, it opens with some errors at the beginning 

Warning: FastBinaryTree not available, using Python version BinaryTree.
Warning: FastAVLTree not available, using Python version AVLTree.
Warning: FastRBTree not available, using Python version RBTree.

i hope you fix these things

**Comment by ehsanmir** [comment]
1- "THERE IS NO GUIDE OF HOW TO INSTALL NILI !!!!":
Just install the prerequisites (See the [README](https://github.com/niloofarkheirkhah/nili/blob/master/README.md) file), Then you can run the setup.py and nili.py:
```
python3 setup.py install
python3 nili.py -h
```

2- "Netzob can not be installed with python3!!!":
You can install netzob with python3 too. If the README file doesn't help, Use these instructions:
```
wget https://pypi.python.org/packages/92/72/c28dd2202efc47e5cf3d883f91638f0b9450a58b5b1d95c5a92c50c514e1/Netzob-1.0.2.tar.gz
tar xf Netzob-1.0.2.tar.gz
cd Netzob-1.0.2
sudo apt-get install python3 python3-dev python3-setuptools build-essential
sudo python3 setup.py install
python3 setup.py develop --user
```

3- "ImportError: No module named netzob!!!":
You can't install netzob with python2 and import it in python3! You have to install it with python3. 

4- "when i try to open nili with python2, it opens with some errors!!!":
They are not errors, They are just warnings, But if you want to get rid of them just upgrade the bintrees:
```
python3 -m pip install bintrees --upgrade
```

**Comment by sasatefa2009** [comment]
thank you ehsanmir, now it works without any problems.

just a small thing you missed
python3 setup.py install
cd nili
python3 nili.py -h
